# Generated by Django 3.2.8 on 2021-11-06 07:04

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Apply',
            fields=[
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('nid', models.IntegerField()),
                ('skills_have', models.TextField()),
                ('skill_want', models.TextField()),
                ('email', models.CharField(max_length=122, primary_key=True, serialize=False)),
                ('password', models.CharField(max_length=122)),
                ('address', models.CharField(max_length=122)),
                ('city', models.CharField(max_length=30)),
                ('zip', models.CharField(max_length=50)),
                ('resume', models.FileField(upload_to='')),
                ('date', models.DateField(default=django.utils.timezone.now)),
            ],
            options={
                'verbose_name_plural': 'Applies',
            },
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=122)),
                ('email', models.CharField(max_length=122)),
                ('subject', models.CharField(max_length=122)),
                ('message', models.TextField()),
                ('date', models.DateField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='Hire',
            fields=[
                ('company_name', models.CharField(max_length=122)),
                ('company_type', models.CharField(max_length=122)),
                ('trade_license', models.FileField(upload_to='')),
                ('email', models.CharField(max_length=122, primary_key=True, serialize=False)),
                ('password', models.CharField(max_length=122)),
                ('address', models.CharField(max_length=122)),
                ('employee_recuirement', models.TextField()),
                ('city', models.CharField(max_length=30)),
                ('zip', models.CharField(max_length=50)),
                ('cc_name', models.CharField(max_length=122)),
                ('cc_number', models.BigIntegerField()),
                ('cc_expiration', models.DateField()),
                ('cc_cvv', models.BigIntegerField()),
                ('date', models.DateField(default=django.utils.timezone.now)),
            ],
            options={
                'verbose_name_plural': 'Hires',
            },
        ),
        migrations.CreateModel(
            name='LoginUser',
            fields=[
                ('email', models.CharField(max_length=122, primary_key=True, serialize=False)),
                ('password', models.CharField(max_length=122)),
                ('date', models.DateField(default=django.utils.timezone.now)),
            ],
            options={
                'verbose_name_plural': 'Login users',
            },
        ),
    ]
